The morph.py library was used in the last two courses at UFABC:

## Processamento Digital de Imagens - PDI - 2023.1
## Visão Computacional e Processamento Imagens - VCPI - 2022.1

# Refs:

1. https://www.dca.fee.unicamp.br/~rubens/adesso/index.html

2. https://www.dca.fee.unicamp.br/~rubens/adesso/Adesso2000/Adesso2000_pp4_final.pdf

3. [livro](https://www.amazon.com.br/Hands-Morphological-Processing-Edward-Dougherty/dp/081944720X)

4. https://github.com/robertoalotufo/ia870

5. https://github.com/robertoalotufo/ia898

6. https://github.com/robertoalotufo/ia870p3

7. see folder [Adesso](https://drive.google.com/drive/folders/1GVEAptj_mU9fA-ff-KDBLBkvBV5giEKW?usp=sharing)

8. ftp://ftp.dca.fee.unicamp.br/pub/cik/morph/morph_doc0.14.pdf

9. https://www.researchgate.net/publication/3922632_Toolbox_of_image_processing_for_numerical_Python

10. https://pythonhosted.org/pymorph/


In [21]:
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import cv2

In [ ]:
!wget https://raw.githubusercontent.com/fzampirolli/morph/main/morph.py -O /dev/null

In [33]:
from morph import *

In [34]:
mm.install(['opencv-python'])

In [35]:
print(cv2.__version__)

3.4.11


In [37]:
help(mm)

Help on class mm in module morph:

class mm(builtins.object)
 |  A helper class for image processing tasks.
 |  
 |  Methods defined here:
 |  
 |  __init__(self)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  blob(f, op='area', border=1, precision=0.01, show='True')
 |      This function will be calculate topology of each connect component
 |      input:
 |        - f: input image
 |        - op: 'area', 'perimeter', etc [default='area']
 |        - border: border of lines [default=1]
 |        - precision: precision of polygonon [default=0.01]
 |        - show=True, return image, else, return measure
 |      output:
 |        - y: image with op or measure
 |  
 |  blobAll(f, border=1, precision=0.01, show='False')
 |      This function will be calculate topology of each connect component
 |      input:
 |        - f: input image
 |        - border: border of lines [default=1]
 |        - precision: precision of polygonon [default=0.01]
 |        - sho

In [39]:
help(mm.ero)

Help on function ero in module morph:

ero(f, Bc=array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8))
    This function will create an erosion of f by Bc
    input:
     - f: input image
     - Bc: structuring element
    output:
     - y: result of filter



In [64]:
import numpy as np
f = np.random.random((5, 10))*10
f = f.astype(int)
print(f)

[[0 7 4 0 4 7 2 9 1 4]
 [8 9 5 4 1 8 3 3 6 5]
 [9 0 7 1 1 4 9 5 9 2]
 [8 0 2 4 6 9 5 6 3 9]
 [3 7 7 3 0 0 5 6 9 2]]


In [65]:
B = np.array([[1,1,1],[0,1,0],[0,0,0]])
B=np.array(B).astype('int8')
print(B)

[[1 1 1]
 [0 1 0]
 [0 0 0]]


In [69]:
g=mm.ero0(f,B)
g[:, [0, -1]] = g[[0, -1], :] = 0 # zero in border
print(g)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 2 1 1 0]
 [0 0 4 1 1 1 3 3 3 0]
 [0 0 0 1 1 1 4 5 2 0]
 [0 0 0 0 0 0 0 0 0 0]]


Note that it is necessary to change the code `ero0` to return the same result as Figure 14 in the paper